# Generated by Django 5.0.6 on 2024-05-13 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id_plantilla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plantilla', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=1200)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOGIN.plantilla')),
            ],
        ),
        migrations.AddField(
            model_name='plantilla',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOGIN.users'),
        ),
    ]
