# Generated by Django 5.0.6 on 2024-05-19 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaAuditorias',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_entidad', models.CharField(max_length=255)),
                ('tipo_entidad', models.CharField(max_length=100)),
                ('sector_industria', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('contacto_entidad_email', models.EmailField(max_length=254)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('duracion_dia', models.IntegerField()),
                ('area_departamento', models.CharField(max_length=255)),
                ('auditor', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=1000)),
                ('fk_plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOGIN.plantilla')),
            ],
        ),
    ]
