# Generated by Django 5.0.6 on 2024-05-19 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0002_agendaauditorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaauditorias',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOGIN.users'),
        ),
    ]
