# Generated by Django 5.0.6 on 2024-05-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0003_alter_agendaauditorias_auditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='id',
        ),
        migrations.AddField(
            model_name='formulario',
            name='id_actividad',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
