# Generated by Django 5.0.6 on 2024-05-20 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0004_remove_formulario_id_formulario_id_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditar',
            fields=[
                ('id_auditar', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_auditoria', models.DateTimeField()),
                ('fecha_fin_auditoria', models.DateTimeField()),
                ('fecha_inicio_plazo', models.DateTimeField()),
                ('estado_auditoria', models.CharField(choices=[('APROBADA', 'Aprobada'), ('REPROBADA', 'Reprobada'), ('EVALUANDO', 'Evaluando')], max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_fin_plazo', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre_auditoria', models.DateTimeField(blank=True, null=True)),
                ('agenda_auditorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOGIN.agendaauditorias')),
            ],
        ),
    ]
