# Generated by Django 5.0.6 on 2024-05-20 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0005_auditar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auditar',
            new_name='Auditoria',
        ),
    ]
