# Generated by Django 5.0.6 on 2024-07-22 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0009_remove_historialauditoria_evaluaciones_actividades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionactividad',
            name='id_actividad',
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='estado_auditoria',
            field=models.CharField(choices=[('EVALUANDO', 'Evaluando')], max_length=10),
        ),
        migrations.AlterField(
            model_name='evaluacionactividad',
            name='auditoria_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacionactividad_set', to='LOGIN.auditoria'),
        ),
    ]
