# Generated by Django 5.0.6 on 2024-07-23 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0010_remove_evaluacionactividad_id_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionactividad',
            name='id_actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LOGIN.formulario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluacionactividad',
            name='auditoria_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOGIN.auditoria'),
        ),
    ]
