# Generated by Django 5.0.6 on 2024-07-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0011_evaluacionactividad_id_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='fecha_inicio_plazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
