# Generated by Django 5.0.6 on 2024-07-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0012_alter_auditoria_fecha_inicio_plazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionactividad',
            name='observaciones',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionactividad',
            name='plazo_fin_observacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionactividad',
            name='plazo_ini_observacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
